name: "Build and Deploy site"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout site repository
        uses: actions/checkout@v3
      - name: build and deploy
        uses: shalzz/zola-deploy-action@v0.16.1-1
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
